#!/bin/bash
echo "🔍 Verificando builds de produção..."
echo ""
[ -f "PORTAL/dist/index.html" ] && echo "✅ PORTAL/dist/index.html" || echo "❌ PORTAL/dist/index.html FALTANDO"
[ -f "PLATAFORMA/dist/index.html" ] && echo "✅ PLATAFORMA/dist/index.html" || echo "❌ PLATAFORMA/dist/index.html FALTANDO"
[ -f "SOLICITE LINK/dist/index.html" ] && echo "✅ SOLICITE LINK/dist/index.html" || echo "❌ SOLICITE LINK/dist/index.html FALTANDO"
echo ""
echo "🔍 Verificando arquivos do sync-server..."
[ -f "sync-server.js" ] && echo "✅ sync-server.js" || echo "❌ sync-server.js FALTANDO"
[ -d "services" ] && echo "✅ services/" || echo "❌ services/ FALTANDO"
[ -d "utils" ] && echo "✅ utils/" || echo "❌ utils/ FALTANDO"
[ -f "package.json" ] && echo "✅ package.json" || echo "❌ package.json FALTANDO"
[ -f ".env" ] && echo "✅ .env" || echo "❌ .env FALTANDO"
echo ""
echo "✅ Verificação concluída!"
