export const ESTADOS_BRASIL = [
  { sigla: "AC", nome: "Acre" },
  { sigla: "AL", nome: "Alagoas" },
  { sigla: "AM", nome: "Amazonas" },
  { sigla: "AP", nome: "Amapá" },
  { sigla: "BA", nome: "Bahia" },
  { sigla: "CE", nome: "Ceará" },
  { sigla: "DF", nome: "Distrito Federal" },
  { sigla: "ES", nome: "Espírito Santo" },
  { sigla: "GO", nome: "Goiás" },
  { sigla: "MA", nome: "Maranhão" },
  { sigla: "MG", nome: "Minas Gerais" },
  { sigla: "MS", nome: "Mato Grosso do Sul" },
  { sigla: "MT", nome: "Mato Grosso" },
  { sigla: "PA", nome: "Pará" },
  { sigla: "PB", nome: "Paraíba" },
  { sigla: "PE", nome: "Pernambuco" },
  { sigla: "PI", nome: "Piauí" },
  { sigla: "PR", nome: "Paraná" },
  { sigla: "RJ", nome: "Rio de Janeiro" },
  { sigla: "RN", nome: "Rio Grande do Norte" },
  { sigla: "RO", nome: "Rondônia" },
  { sigla: "RR", nome: "Roraima" },
  { sigla: "RS", nome: "Rio Grande do Sul" },
  { sigla: "SC", nome: "Santa Catarina" },
  { sigla: "SE", nome: "Sergipe" },
  { sigla: "SP", nome: "São Paulo" },
  { sigla: "TO", nome: "Tocantins" },
];

export const COMARCAS_RJ = [
  "Angra dos Reis",
  "Araruama",
  "Armação dos Búzios",
  "Arraial do Cabo",
  "Barra do Piraí",
  "Barra Mansa",
  "Belford Roxo",
  "Bom Jardim",
  "Bom Jesus do Itabapoana",
  "Cabo Frio",
  "Cachoeiras de Macacu",
  "Cambuci",
  "Campos dos Goytacazes",
  "Cantagalo",
  "Carmo",
  "Casimiro de Abreu",
  "Conceição de Macabu",
  "Cordeiro",
  "Duas Barras",
  "Duque de Caxias",
  "Engenheiro Paulo de Frontin",
  "Guapimirim",
  "Iguaba Grande",
  "Itaboraí",
  "Itaguaí",
  "Italva",
  "Itaocara",
  "Itaperuna",
  "Itatiaia",
  "Japeri",
  "Laje do Muriaé",
  "Macaé",
  "Magé",
  "Mangaratiba",
  "Maricá",
  "Mendes",
  "Mesquita",
  "Miguel Pereira",
  "Miracema",
  "Natividade",
  "Nilópolis",
  "Niterói",
  "Nova Friburgo",
  "Nova Iguaçu",
  "Paracambi",
  "Paraíba do Sul",
  "Paraty",
  "Paty do Alferes",
  "Petrópolis",
  "Pinheiral",
  "Piraí",
  "Porciúncula",
  "Porto Real",
  "Quatis",
  "Queimados",
  "Quissamã",
  "Resende",
  "Rio Bonito",
  "Rio Claro",
  "Rio das Flores",
  "Rio das Ostras",
  "Rio de Janeiro",
  "Santa Maria Madalena",
  "Santo Antônio de Pádua",
  "São Fidélis",
  "São Francisco de Itabapoana",
  "São Gonçalo",
  "São João da Barra",
  "São João de Meriti",
  "São José de Ubá",
  "São José do Vale do Rio Preto",
  "São Pedro da Aldeia",
  "São Sebastião do Alto",
  "Sapucaia",
  "Saquarema",
  "Seropédica",
  "Silva Jardim",
  "Sumidouro",
  "Tanguá",
  "Teresópolis",
  "Trajano de Moraes",
  "Três Rios",
  "Valença",
  "Vassouras",
  "Volta Redonda",
];

/** Comarcas do TJMG - Certidão de Distribuição (valor = formato Plexi API) */
export const COMARCAS_MG = [
  { value: "beloHorizonte", label: "Belo Horizonte" },
  { value: "contagem", label: "Contagem" },
  { value: "betim", label: "Betim" },
  { value: "divinopolis", label: "Divinópolis" },
  { value: "barbacena", label: "Barbacena" },
  { value: "juizDeFora", label: "Juiz de Fora" },
  { value: "uberlandia", label: "Uberlândia" },
  { value: "montesClaros", label: "Montes Claros" },
  { value: "governadorValadares", label: "Governador Valadares" },
  { value: "pousoAlegre", label: "Pouso Alegre" },
  { value: "araxa", label: "Araxá" },
  { value: "araguari", label: "Araguari" },
  { value: "congonhas", label: "Congonhas" },
  { value: "conselheiroLafaiete", label: "Conselheiro Lafaiete" },
  { value: "coronelFabriciano", label: "Coronel Fabriciano" },
  { value: "ipatinga", label: "Ipatinga" },
  { value: "itauna", label: "Itaúna" },
  { value: "passos", label: "Passos" },
  { value: "patosDeMinas", label: "Patos de Minas" },
  { value: "pocosDeCaldas", label: "Poços de Caldas" },
  { value: "santaLuzia", label: "Santa Luzia" },
  { value: "seteLagoas", label: "Sete Lagoas" },
  { value: "teofiloOtoni", label: "Teófilo Otoni" },
  { value: "varginha", label: "Varginha" },
  { value: "alfenas", label: "Alfenas" },
  { value: "caratinga", label: "Caratinga" },
  { value: "curvelo", label: "Curvelo" },
  { value: "diamantina", label: "Diamantina" },
];

/** Comarcas do Tribunal de Justiça de Mato Grosso do Sul (TJMS - SAJ) */
export const COMARCAS_MS = [
  "Campo Grande",
  "Corumbá",
  "Dourados",
  "Três Lagoas",
  "Ponta Porã",
  "Naviraí",
  "Aquidauana",
  "Coxim",
  "Maracaju",
  "Paranaíba",
  "Rio Brilhante",
  "Amambai",
  "Nova Andradina",
  "Jardim",
  "Sidrolândia",
  "Bela Vista",
  "Bonito",
  "Caarapó",
  "Chapadão do Sul",
  "Iguatemi",
  "Itaporã",
  "Ladário",
  "Miranda",
  "Mundo Novo",
  "São Gabriel do Oeste",
  "Sonora",
  "Outras",
];

export const FINALIDADES_RJ = [
  "Ação de Tutela",
  "Adoção",
  "Alienação Fiduciária",
  "Aluguel",
  "Apresentação à Polícia Federal",
  "Autorização de Viagem",
  "Cadastro",
  "Carteira Profissional",
  "Concursos Públicos",
  "Credenciamento",
  "Emprego",
  "Estágio",
  "Financiamento",
  "Inscrição em Conselho Profissional",
  "Instrução de Processo Administrativo",
  "Instrução de Processo Judicial",
  "Licitação",
  "Naturalização",
  "Ordem Judicial",
  "Posse em Cargo Público",
  "Porte de Arma",
  "Prova de Vida",
  "Registro em Órgão Público",
  "Seguro",
  "Transferência de Imóvel",
  "Universidade / Faculdade",
  "Visto / Migração",
];

export const CIDADES_SE = [
  "Aracaju",
  "Barra dos Coqueiros",
  "Boquim",
  "Capela",
  "Carira",
  "Estância",
  "Itabaiana",
  "Itabaianinha",
  "Lagarto",
  "Laranjeiras",
  "Maruim",
  "Nossa Senhora da Glória",
  "Nossa Senhora das Dores",
  "Nossa Senhora do Socorro",
  "Poço Verde",
  "Porto da Folha",
  "Propriá",
  "Riachão do Dantas",
  "Ribeirópolis",
  "Simão Dias",
  "Tobias Barreto",
];

export const PAISES = [
  "Brasil",
  "Portugal",
  "Espanha",
  "Itália",
  "Alemanha",
  "França",
  "Estados Unidos",
  "Argentina",
  "Japão",
  "Outro",
];

export const ESTADOS_CIVIS = [
  "Solteiro(a)",
  "Casado(a)",
  "Divorciado(a)",
  "Viúvo(a)",
  "União Estável",
];

/** Estado civil completo (Piauí e outros que exigem Separado/Outros) */
export const ESTADOS_CIVIS_PI = [
  "Solteiro(a)",
  "Casado(a)",
  "Divorciado(a)",
  "Viúvo(a)",
  "Separado(a)",
  "União estável",
  "Outros",
];

export const NACIONALIDADES = [
  "Brasileiro(a)",
  "Naturalizado(a)",
  "Estrangeiro(a)",
];
